server:
  port: 8183

spring:
  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: housekeeping-svc
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.oktank.reservation.ReservationCreated
        spring.json.trusted.packages: com.oktank.*
        spring.json.use.type.headers: false

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: com.oktank.*

    listener:
      ack-mode: batch

app:
  topics:
    reservationCreated: reservations.created
