name: CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Build all services
        run: |
          for svc in services/*-service; do
            echo "Building $svc"
            (cd "$svc" && mvn -q -B -DskipTests package)
          done
